---
title: "Data Science Experiments"
author: "Himanshu Singh"
date: "09/02/2021"
output: html_document
---

library(tidyverse)
library(gganimate)
Df <- read.csv ("C:/Users/Himanshu Singh/Desktop/full_grouped.csv", header =T)

view(Df)

Death_grp <-Df %>%
  group_by(Date,Country.Region) %>%
  summarise(totalDeath = sum(Deaths)) %>%
  ungroup()

view(Death_grp)

Death_grp <- as.data.frame(Death_grp) %>%
  group_by(Date) %>%
  mutate(rank = rank(-totalDeath),
         Value_lbl = paste0(" ",totalDeath)) %>%
  group_by(Country.Region) %>% 
  filter(rank <=15) %>%
  ungroup()
  
view(Death_grp)

staticplot = ggplot(Death_grp, aes(rank, group = Country.Region, 
                    fill = as.factor(Country.Region), color = as.factor(Country.Region))) +
  geom_tile(aes(y = totalDeath/2,height = totalDeath,width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(Country.Region, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y=totalDeath,label = Value_lbl, hjust=0)) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.position="none",
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.grid.major.x = element_line( size=.1, color="grey" ),
        panel.grid.minor.x = element_line( size=.1, color="grey" ),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="grey", vjust=-1),
        plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="grey"),
        plot.caption =element_text(size=8, hjust=0.5, face="italic", color="grey"),
        plot.background=element_blank(),
        plot.margin = margin(2,2, 2, 4, "cm"))

staticplot

anim = staticplot + transition_states(Date, transition_length = 4, state_length = 1) +
  view_follow(fixed_x = TRUE)  +
  labs(title = 'Total Death Date-Wise : {closest_state}',  
       subtitle  =  "Top 15 Countries",
       caption  = "Death Cases")
animate(anim, 1000, fps = 20,  width = 1200, height = 1000, 
        renderer = gifski_renderer("Death.gif"))
anim